
{# [dash:data]
  {
    "status": "development",
    "category": "page",
    "label": "Comingsoon",
    "link": "../../comingsoon.html"
  }
  [/dash] #}

{% extends './layouts/base.swig' %}

{% block content %}
<section id="projects" class="content m-scene">
  <div class="container">
  	<div class="row">
    	<div class="col-sm-10 col-sm-offset-1">
      	<h1>Hello World</h1>
    	</div>
  	</div>
  </div>
</section>
{% endblock %}
